"""schema initial : utilisateurs, distributions, workers, instances, locations

Identifiant : d8c810a4813f
Précédente  : aucune (schéma initial)
Créée le    : 2026-09-30 15:32:40.574730
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# Identifiants de révision utilisés par Alembic
revision: str = 'd8c810a4813f'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Applique la migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('docker_image', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('hint', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index('idx_attempts_recent', ['created_at', 'username', 'ip'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ssh_public_key', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=64), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('cpu', sa.Integer(), nullable=True),
    sa.Column('memory', sa.Integer(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname')
    )
    op.create_table('instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.String(length=64), nullable=False),
    sa.Column('container_name', sa.String(length=64), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('distribution_id', sa.Integer(), nullable=False),
    sa.Column('ssh_port', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('term_port', sa.Integer(), nullable=True),
    sa.Column('gui_port', sa.Integer(), nullable=True),
    sa.Column('root_password', sa.Text(), nullable=True),
    sa.Column('terminated_at', sa.DateTime(), nullable=True),
    sa.Column('migrations', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['distribution_id'], ['distributions.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instances', schema=None) as batch_op:
        batch_op.create_index('idx_instances_status', ['status'], unique=False)
        batch_op.create_index('uq_worker_port_actif', ['worker_id', 'ssh_port'], unique=True, sqlite_where=sa.text("status = 'running'"), postgresql_where=sa.text("status = 'running'"))

    op.create_table('rentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.create_index('idx_rentals_end', ['status', 'end_time'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revient à l'état précédent."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.drop_index('idx_rentals_end')

    op.drop_table('rentals')
    with op.batch_alter_table('instances', schema=None) as batch_op:
        batch_op.drop_index('uq_worker_port_actif', sqlite_where=sa.text("status = 'running'"), postgresql_where=sa.text("status = 'running'"))
        batch_op.drop_index('idx_instances_status')

    op.drop_table('instances')
    op.drop_table('workers')
    op.drop_table('users')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index('idx_attempts_recent')

    op.drop_table('login_attempts')
    op.drop_table('distributions')
    # ### end Alembic commands ###
